[package]
name = "sorrow"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["boot"]

[lib]
name = "lib_sorrow"
path = "src/lib.rs"

[[test]]
name = "should_panic"
harness = false

[dependencies]
bootloader =  "0.10.10"
conquer-once = { version = "0.3.2", default-features = false }
crossbeam-queue = { version = "0.3.2", features = ["alloc"], default-features = false }
futures-util = { version = "0.3.19", features = ["alloc"], default-features = false }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
linked_list_allocator = "0.9.1"
pc-keyboard = "0.5.1"
pic8259 = "0.10.2"
spin = "0.9.2"
uart_16550 = "0.2.15"
volatile = "0.4.4"
x86_64 = "0.14.7"
